export const POST_VOLUNTARY = 'POST_VOLUNTARY';



export const GET_STUDENTS = "GET_STUDENTS";
export const GET_STUDENT_DETAIL = "GET_STUDENT_DETAIL"
export const ADD_STUDENT = "ADD_STUDENT";
export const EDIT_STUDENT ="EDIT_STUDENT";

export const GET_SUBJECTS = "GET_SUBJECTS";
export const GET_SUBJECT_DETAIL = "GET_SUBJECT_DETAIL";
export const EDIT_SUBJECT = "EDIT_SUBJECT";
export const ADD_SUBJECT = "ADD_SUBJECT";
export const DELETE_SUBJECT ="DELETE_SUBJECT";