export const POST_VOLUNTARY = 'POST_VOLUNTARY';



export const GET_STUDENTS = "GET_STUDENTS";
export const GET_STUDENT_DETAIL = "GET_STUDENT_DETAIL"
export const ADD_STUDENT = "ADD_STUDENT";
export const EDIT_STUDENT ="EDIT_STUDENT";