// Voluntarios - DELETE se representa con deshabilitado.
export const ADD_VOLUNTARY = 'ADD_VOLUNTARY';
export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const ADD_SUBJECTS_VOLUNTEER = 'ADD_SUBJECTS_VOLUNTEER';
export const GET_VOLUNTEERS = 'GET_VOLUNTEERS';
export const DELETE_VOLUNTEER = 'DELETE_VOLUNTEER';
export const ACCEPT_VOLUNTEER = 'ACCEPT_VOLUNTEER';

// Alumnos - DELETE se representa con deshabilitado.
export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_STUDENT_DETAIL = 'GET_STUDENT_DETAIL';
export const ADD_STUDENT = 'ADD_STUDENT';
export const PUT_STUDENT = 'PUT_STUDENT';

// Materias
export const GET_SUBJECTS = 'GET_SUBJECTS';
export const GET_SUBJECT_DETAIL = 'GET_SUBJECT_DETAIL';
export const PUT_SUBJECT = 'PUT_SUBJECT';
export const ADD_SUBJECT = 'ADD_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

// Dificultades
export const ADD_DIFFICULTY = 'ADD_DIFFICULTY';
export const PUT_DIFFICULTY = 'PUT_DIFFICULTY';
export const GET_DIFFICULTIES = 'GET_DIFFICULTIES';
export const GET_DIFFICULTY_DETAIL = 'GET_DIFFICULTY_DETAIL';
export const DELETE_DIFFICULTY = 'DELETE_DIFFICULTY';

// export const GET_USERS = "GET_USERS";
export const GET_ALL_ASSISTANCE = "GET_ALL_ASSISTANCE";
export const GET_ASSISTANCE_STUDENT = "GET_ASSISTANCE_STUDENT";

// EDUCATION LEVELS
export const ADD_EDUCATION_LEVELS = 'ADD_EDUCATION_LEVELS';
export const PUT_EDUCATION_LEVELS = 'PUT_EDUCATION_LEVELS';
export const GET_EDUCATION_LEVELS = 'GET_EDUCATION_LEVELS';
export const GET_EDUCATION_LEVELS_DETAIL = 'GET_EDUCATION_LEVELS_DETAIL';
export const DELETE_EDUCATION_LEVELS = 'DELETE_EDUCATION_LEVELS';

// Niveles academicos
export const GET_ACADEMIC_LEVELS = 'GET_ACADEMIC_LEVELS';
export const GET_USERS = "GET_USERS"
export const FILTER_BY_LEVEL = "FILTER_BY_LEVEL"

// Clases

export const GET_MATCHING_SCHEDULES = "GET_MATCHING_SCHEDULES"
export const DELETE_CLASS_FROM_STUDENT = "DELETE_CLASS_FROM_STUDENT"
